spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:host.docker.internal}:3306/${DB_NAME:wxnotion}?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  sql:
    init:
      mode: never
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
server:
  port: 8080
